// Places to go from California colleges, picked for being unique (not just "a city"): ghost towns,
// hot springs, tufa towers, condor caves, glass beaches, dark-sky deserts… plus the classics.
// Each place: id, name, lat, lon, area (season profile in build-us.mjs), tags (interest keys),
//   fee: entrance or parking per car ($), ticket: per person (ferries, tours) ($),
//   stay: where students sleep ("camp" | "hostel" | "motel" | "cabin" | null for short local visits),
//   trip: "local" (an afternoon near campus), "both" (day trip or weekend), "weekend" (needs a night),
//         "long" (3+ days), note, days (a plan per day), wiki (Wikipedia title for photos and checks).
// Coordinates are approximate; the data job checks them against Wikipedia.
export const PLACES = [
  // ---------------------------------------------------------------- Bay Area and north coast
  { id: "point-reyes", name: "Point Reyes", lat: 38.0690, lon: -122.8069, area: "coast", tags: ["nature", "wildlife", "hiking", "beach", "views", "food"], fee: 0, stay: "camp", trip: "both",
    note: "Tule elk on the bluffs, a lighthouse 300 steps down a cliff, and oysters on Tomales Bay.",
    days: ["Tomales Point trail through the elk herd, then oysters in Marshall", "Point Reyes Lighthouse and Chimney Rock; sunset at Drakes Beach"], wiki: "Point_Reyes_National_Seashore" },
  { id: "muir-woods", name: "Muir Woods & Mount Tam", lat: 37.8970, lon: -122.5811, area: "bay", tags: ["nature", "hiking", "views"], fee: 15, stay: "camp", trip: "both",
    note: "Old-growth redwoods in a canyon, then the sunset over the fog from Mount Tamalpais.",
    days: ["Muir Woods loop (reserve parking), then Dipsea trail toward Stinson Beach", "Sunrise at Mount Tam's East Peak, then the Steep Ravine cabins trail"], wiki: "Muir_Woods_National_Monument" },
  { id: "stinson-beach", name: "Stinson Beach", lat: 37.9005, lon: -122.6444, area: "bay", tags: ["beach", "views", "hiking"], fee: 0, stay: null, trip: "local",
    note: "A long sandy beach under Mount Tam, reached by one of the curviest roads in the Bay.",
    days: ["Drive Highway 1's switchbacks, beach afternoon, fish tacos in town"], wiki: "Stinson_Beach,_California" },
  { id: "marin-headlands", name: "Marin Headlands", lat: 37.8155, lon: -122.5299, area: "bay", tags: ["views", "hiking", "history", "beach"], fee: 0, stay: null, trip: "local",
    note: "The postcard Golden Gate view from Battery Spencer and a lighthouse on a suspension bridge.",
    days: ["Battery Spencer view, Point Bonita Lighthouse, then Rodeo Beach at sunset"], wiki: "Marin_Headlands" },
  { id: "lands-end", name: "Lands End & Sutro Baths", lat: 37.7804, lon: -122.5138, area: "bay", tags: ["views", "hiking", "history", "offbeat"], fee: 0, stay: null, trip: "local",
    note: "Ruins of a giant Victorian bathhouse, a cliff trail and a hidden stone labyrinth.",
    days: ["Sutro Baths ruins, the Lands End labyrinth, then the Camera Obscura and Ocean Beach"], wiki: "Lands_End_(San_Francisco)" },
  { id: "san-francisco", name: "San Francisco", lat: 37.7749, lon: -122.4194, area: "city", tags: ["food", "art", "history", "nightlife", "views", "streetart", "film", "lgbtq", "vintage"], fee: 25, stay: "hostel", trip: "both",
    note: "Mission burritos and murals, cable cars, the Castro and fog rolling over Twin Peaks.",
    days: ["Mission murals on Balmy Alley, a burrito in Dolores Park, Castro at night", "Walk the Golden Gate Bridge, Presidio Tunnel Tops, dim sum in the Richmond"], wiki: "San_Francisco" },
  { id: "angel-island", name: "Angel Island", lat: 37.8609, lon: -122.4325, port: [37.8735, -122.4567, "Tiburon"], area: "bay", tags: ["islands", "hiking", "history", "views", "cycling"], fee: 0, ticket: 20, stay: "camp", trip: "both",
    note: "A ferry to a car-free island with 360° bay views and the immigration station's poems.",
    days: ["Ferry from Tiburon, bike the perimeter road, the Immigration Station museum", "Hike Mount Livermore at sunrise (if camping), ferry back"], wiki: "Angel_Island_(California)" },
  { id: "half-moon-bay", name: "Half Moon Bay & Pescadero", lat: 37.4636, lon: -122.4286, area: "coast", tags: ["beach", "food", "villages", "hiking", "wildlife"], fee: 0, stay: "camp", trip: "both",
    note: "Tide pools at Fitzgerald Marine Reserve and warm artichoke bread in tiny Pescadero.",
    days: ["Fitzgerald tide pools at low tide, Pillar Point bluff, Mavericks", "Pescadero's Arcangeli bakery, Pigeon Point Lighthouse, Bean Hollow's pebble beach"], wiki: "Half_Moon_Bay,_California" },
  { id: "ano-nuevo", name: "Año Nuevo elephant seals", lat: 37.1083, lon: -122.3372, area: "coast", tags: ["wildlife", "nature", "beach", "offbeat"], fee: 10, ticket: 12, stay: null, trip: "both",
    note: "Two-ton elephant seals fighting and giving birth on the dunes (guided walks Dec–Mar).",
    days: ["Guided walk to the seal colony, then Bonny Doon's Panther Beach arch"], wiki: "Año_Nuevo_State_Park" },
  { id: "mission-peak", name: "Mission Peak", lat: 37.5126, lon: -121.8810, area: "valley", tags: ["hiking", "views"], fee: 0, stay: null, trip: "local",
    note: "The Bay Area's most-climbed summit and its famous pole; go at sunrise.",
    days: ["Sunrise hike to the summit pole, breakfast in Fremont's Niles district"], wiki: "Mission_Peak" },
  { id: "castle-rock", name: "Castle Rock & Skyline", lat: 37.2302, lon: -122.0961, area: "bay", tags: ["hiking", "climbing", "views", "nature"], fee: 10, stay: null, trip: "local",
    note: "Sandstone caves and boulders on the ridge between Silicon Valley and the ocean.",
    days: ["Castle Rock Falls overlook, Goat Rock climbers, Alice's Restaurant for lunch"], wiki: "Castle_Rock_State_Park_(California)" },
  { id: "santa-cruz", name: "Santa Cruz", lat: 36.9741, lon: -122.0308, area: "coast", tags: ["beach", "surf", "themeparks", "hiking", "nature", "vintage"], fee: 10, stay: "hostel", trip: "both",
    note: "A 1907 boardwalk roller coaster, surfers at Steamer Lane and redwoods ten minutes inland.",
    days: ["Boardwalk rides, West Cliff Drive to Natural Bridges at sunset", "Henry Cowell's redwood loop, Roaring Camp steam train, thrifting on Pacific Ave"], wiki: "Santa_Cruz,_California" },
  { id: "henry-cowell", name: "Henry Cowell Redwoods", lat: 37.0405, lon: -122.0586, area: "bay", tags: ["nature", "hiking"], fee: 10, stay: null, trip: "local",
    note: "A flat redwood loop with a tree you can stand inside, ten minutes from UCSC.",
    days: ["Redwood Grove loop, the Observation Deck trail, swim at the river beach in summer"], wiki: "Henry_Cowell_Redwoods_State_Park" },
  { id: "monterey-carmel", name: "Monterey & Carmel", lat: 36.6002, lon: -121.8947, area: "coast", tags: ["wildlife", "food", "villages", "views", "beach", "history"], fee: 0, stay: "motel", trip: "both",
    note: "Sea otters on kelp, 17-Mile Drive and Carmel's fairytale cottages.",
    days: ["Kayak with sea otters, Cannery Row, clam chowder on the wharf", "Point Lobos at opening, Carmel Beach, the Mission"], wiki: "Monterey,_California" },
  { id: "elkhorn-slough", name: "Elkhorn Slough", lat: 36.8180, lon: -121.7470, area: "coast", tags: ["wildlife", "nature", "offbeat"], fee: 0, ticket: 45, stay: null, trip: "local",
    note: "Kayak past dozens of sea otters and harbor seals in a quiet estuary.",
    days: ["Kayak rental at Moss Landing, otters up close, then Phil's Fish Market"], wiki: "Elkhorn_Slough" },
  { id: "big-sur", name: "Big Sur", lat: 36.2704, lon: -121.8081, area: "coast", tags: ["hiking", "views", "nature", "beach", "offbeat"], fee: 10, stay: "camp", trip: "both",
    note: "McWay Falls dropping onto a beach, Bixby Bridge and the purple sand at Pfeiffer Beach.",
    days: ["Bixby Bridge, Pfeiffer Beach's keyhole arch, Big Sur Bakery", "McWay Falls at Julia Pfeiffer Burns, Limekiln redwoods and kilns"], wiki: "Big_Sur" },
  { id: "pinnacles", name: "Pinnacles National Park", lat: 36.4906, lon: -121.1825, area: "valley", tags: ["hiking", "caves", "wildlife", "climbing", "nature"], fee: 30, stay: "camp", trip: "both",
    note: "Crawl through talus caves with a flashlight while California condors circle above.",
    days: ["Bear Gulch Cave and the reservoir, then the High Peaks loop", "Balconies Cave, stargazing from the campground"], wiki: "Pinnacles_National_Park" },
  { id: "sonoma", name: "Sonoma Valley", lat: 38.2919, lon: -122.4580, area: "wine", tags: ["wine", "food", "cycling", "villages", "history"], fee: 0, stay: "motel", trip: "both",
    note: "Bike between family wineries, then picnic on Sonoma's mission plaza.",
    days: ["Bike rental in Sonoma, two tastings (many waive fees with purchase), plaza picnic", "Jack London State Park's ruins, Glen Ellen"], wiki: "Sonoma_Valley" },
  { id: "calistoga", name: "Calistoga & Napa", lat: 38.5788, lon: -122.5797, area: "wine", tags: ["wine", "spas", "food", "nature"], fee: 0, stay: "motel", trip: "both",
    note: "Volcanic mud baths, an erupting geyser and the valley's grand wineries.",
    days: ["Mud bath in Calistoga, the Old Faithful Geyser, Petrified Forest", "Castello di Amorosa, Oxbow Public Market in Napa"], wiki: "Calistoga,_California" },
  { id: "russian-river", name: "Russian River & Armstrong Redwoods", lat: 38.5390, lon: -123.0090, area: "wine", tags: ["lakes", "nature", "wine", "hiking", "lgbtq"], fee: 10, stay: "camp", trip: "both",
    note: "Float the river on an inner tube under giant redwoods, then Guerneville at night.",
    days: ["Armstrong Redwoods' Colonel Armstrong tree, river float from Johnson's Beach", "Healdsburg plaza and a Dry Creek winery"], wiki: "Armstrong_Redwoods_State_Natural_Reserve" },
  { id: "bodega-bay", name: "Bodega Bay & Sonoma Coast", lat: 38.3332, lon: -123.0481, area: "coast", tags: ["views", "beach", "wildlife", "film", "hiking"], fee: 0, stay: "camp", trip: "both",
    note: "Where Hitchcock filmed The Birds: whale-watching headlands and secret coves.",
    days: ["Bodega Head whale watch, the schoolhouse from The Birds", "Goat Rock's seal colony at the river mouth, Shell Beach tide pools"], wiki: "Bodega_Bay,_California" },
  { id: "mendocino", name: "Mendocino & Glass Beach", lat: 39.3076, lon: -123.7995, area: "north_coast", tags: ["villages", "beach", "views", "offbeat", "hiking"], fee: 0, stay: "camp", trip: "weekend",
    note: "A Victorian village on the cliffs and a beach paved with sea glass in Fort Bragg.",
    days: ["Mendocino Headlands, the village's water towers, Van Damme's fern canyon", "Glass Beach in Fort Bragg, Point Cabrillo Lighthouse"], wiki: "Mendocino,_California" },
  { id: "berryessa", name: "Lake Berryessa", lat: 38.5130, lon: -122.1050, area: "valley", tags: ["lakes", "offbeat", "views"], fee: 0, stay: null, trip: "local",
    note: "The 'glory hole' spillway drain that looks like a portal in the lake.",
    days: ["Monticello Dam's glory hole viewpoint, swim at Oak Shores"], wiki: "Lake_Berryessa" },
  // ---------------------------------------------------------------- Sacramento, Gold Country, Sierra
  { id: "sacramento", name: "Sacramento", lat: 38.5816, lon: -121.4944, area: "valley", tags: ["history", "food", "markets", "cycling"], fee: 0, stay: "hostel", trip: "both",
    note: "Gold Rush boardwalks in Old Sacramento and the farm-to-fork capital's food halls.",
    days: ["Old Sacramento and the railroad museum, the Capitol", "Bike the American River trail, the Midtown farmers market"], wiki: "Sacramento,_California" },
  { id: "locke-delta", name: "Locke & the Delta", lat: 38.2507, lon: -121.5072, area: "valley", tags: ["history", "offbeat", "villages", "food"], fee: 0, stay: null, trip: "local",
    note: "The last rural Chinatown in the US, on a levee road through the river delta.",
    days: ["Locke's wooden main street, Al the Wop's bar, delta drive to Isleton"], wiki: "Locke,_California" },
  { id: "american-river", name: "Folsom & American River", lat: 38.6780, lon: -121.1760, area: "valley", tags: ["lakes", "cycling", "hiking", "history"], fee: 0, stay: null, trip: "local",
    note: "Rafting and paddleboarding near Sacramento, and Johnny Cash's Folsom Prison museum.",
    days: ["Paddleboard Lake Natoma, Folsom's historic district"], wiki: "American_River" },
  { id: "nevada-city", name: "Nevada City & South Yuba", lat: 39.2616, lon: -121.0161, area: "foothills", tags: ["history", "villages", "lakes", "hiking", "vintage"], fee: 0, stay: "camp", trip: "both",
    note: "A gaslit Gold Rush town and emerald swimming holes on the South Yuba River.",
    days: ["Swim at the Bridgeport covered bridge, Empire Mine", "Nevada City's Broad Street, the Independence Trail"], wiki: "Nevada_City,_California" },
  { id: "columbia", name: "Columbia State Historic Park", lat: 38.0352, lon: -120.4005, area: "foothills", tags: ["history", "villages", "offbeat"], fee: 0, stay: "camp", trip: "both",
    note: "Pan for gold and ride a stagecoach in a preserved 1850s mining town.",
    days: ["Gold panning, stagecoach ride, sarsaparilla in the saloon", "Moaning Cavern's rappel or Mercer Caverns"], wiki: "Columbia_State_Historic_Park" },
  { id: "lake-tahoe", name: "Lake Tahoe", lat: 38.9540, lon: -120.1000, area: "sierra", tags: ["lakes", "hiking", "snow", "views", "beach", "mountains"], fee: 10, stay: "cabin", trip: "weekend",
    note: "Emerald Bay's island teahouse, clear-water beaches in summer, ski slopes in winter.",
    days: ["Emerald Bay and Vikingsholm, Eagle Falls, sunset at Sand Harbor", "Rent a kayak at Kings Beach, or ski at a resort with a student pass"], wiki: "Lake_Tahoe" },
  { id: "truckee", name: "Truckee & Donner Lake", lat: 39.3280, lon: -120.1833, area: "snow", tags: ["snow", "lakes", "history", "hiking", "mountains"], fee: 0, stay: "cabin", trip: "weekend",
    note: "Old railroad town, the Donner Party story and the old tunnels on Donner Summit.",
    days: ["Hike the old Donner Summit railroad tunnels, Rainbow Bridge", "Donner Lake beach (or sledding), downtown Truckee"], wiki: "Truckee,_California" },
  { id: "yosemite", name: "Yosemite Valley", lat: 37.7456, lon: -119.5936, area: "sierra", tags: ["hiking", "nature", "views", "climbing", "camping", "mountains"], fee: 35, stay: "camp", trip: "both",
    note: "Half Dome, El Capitan's climbers and the Mist Trail beside two thundering waterfalls.",
    days: ["Mist Trail to Vernal and Nevada Falls", "Tunnel View at sunrise, Mariposa Grove's giant sequoias, Glacier Point sunset (summer)"], wiki: "Yosemite_Valley" },
  { id: "mono-lake", tioga: true, name: "Mono Lake & Bodie", lat: 37.9416, lon: -119.0271, area: "sierra_high", tags: ["offbeat", "history", "nature", "views", "film", "stargazing"], fee: 10, stay: "camp", trip: "weekend",
    note: "Alien tufa towers rising from a salt lake, and Bodie, a ghost town frozen in 1880.",
    days: ["South Tufa at sunrise, Panum Crater, Whoa Nellie Deli in a gas station", "Bodie ghost town (the road closes in snow), June Lake loop"], wiki: "Mono_Lake" },
  { id: "mammoth", tioga: true, name: "Mammoth Lakes", lat: 37.6485, lon: -118.9721, area: "snow", tags: ["snow", "hiking", "lakes", "mountains", "spas"], fee: 0, stay: "cabin", trip: "weekend",
    note: "Ski into June, then soak in wild hot springs with the Sierra at sunset.",
    days: ["Devils Postpile and Rainbow Falls (summer) or skiing (winter)", "Wild Willy's hot spring at sunrise, Convict Lake"], wiki: "Mammoth_Lakes,_California" },
  { id: "bishop", tioga: true, name: "Bishop & the Buttermilks", lat: 37.3635, lon: -118.3951, area: "high_desert", tags: ["climbing", "spas", "hiking", "food", "stargazing"], fee: 0, stay: "camp", trip: "weekend",
    note: "World-class bouldering, Keough's hot springs and Erick Schat's famous bakery.",
    days: ["Boulder in the Buttermilks at golden hour, Schat's bakery", "Keough's Hot Springs, Ancient Bristlecone Pine Forest (summer)"], wiki: "Bishop,_California" },
  { id: "alabama-hills", name: "Alabama Hills & Lone Pine", lat: 36.6080, lon: -118.1270, area: "high_desert", tags: ["film", "hiking", "views", "climbing", "camping", "stargazing", "desert"], fee: 0, stay: "camp", trip: "weekend",
    note: "Free camping among the rock arches where hundreds of westerns were filmed, under Mount Whitney.",
    days: ["Mobius Arch at sunrise, Movie Road, the Museum of Western Film History", "Whitney Portal's waterfall and hike, or Manzanar National Historic Site"], wiki: "Alabama_Hills" },
  { id: "sequoia", name: "Sequoia National Park", lat: 36.4864, lon: -118.5658, area: "sierra", tags: ["nature", "hiking", "views", "caves", "mountains"], fee: 35, stay: "camp", trip: "both",
    note: "The General Sherman tree, the granite stairs up Moro Rock and a marble cave (seasonal tours).",
    days: ["General Sherman, the Congress Trail, Moro Rock at sunset", "Crystal Cave tour (summer, when open), Tunnel Log"], wiki: "Sequoia_National_Park" },
  { id: "kings-canyon", name: "Kings Canyon", lat: 36.7466, lon: -118.9725, area: "sierra", tags: ["nature", "hiking", "views", "mountains", "lakes"], fee: 35, stay: "camp", trip: "weekend",
    note: "A canyon deeper than the Grand Canyon, with fewer people than Yosemite.",
    days: ["General Grant Grove, Panoramic Point", "Drive Highway 180 into the canyon, Mist Falls, Zumwalt Meadow (summer)"], wiki: "Kings_Canyon_National_Park" },
  { id: "kern-river", name: "Kern River (Kernville)", lat: 35.7550, lon: -118.4250, area: "foothills", tags: ["surf", "lakes", "hiking", "camping"], fee: 0, ticket: 60, stay: "camp", trip: "both",
    note: "Whitewater rafting through a granite canyon, a few hours from LA.",
    days: ["Half-day rafting trip, camp by the river", "Trail of 100 Giants sequoias (summer), Kernville brewery"], wiki: "Kern_River" },
  { id: "lassen", name: "Lassen Volcanic", lat: 40.4977, lon: -121.4207, area: "sierra_high", tags: ["hiking", "lakes", "spas", "desert", "nature", "mountains"], fee: 30, stay: "camp", trip: "weekend",
    note: "Boiling mud pots and steam vents at Bumpass Hell, and a summit hike on a volcano.",
    days: ["Bumpass Hell boardwalk, Lake Helen, Lassen Peak trail (summer)", "Cinder Cone's painted dunes, Manzanita Lake at sunset"], wiki: "Lassen_Volcanic_National_Park" },
  { id: "burney-falls", name: "Burney Falls & Subway Cave", lat: 41.0122, lon: -121.6513, area: "sierra", tags: ["nature", "caves", "hiking", "lakes"], fee: 10, stay: "camp", trip: "weekend",
    note: "A waterfall that pours out of the rock face, and a lava tube you walk through in the dark.",
    days: ["Burney Falls loop trail, swim in Lake Britton", "Subway Cave lava tube (bring a flashlight), Hat Creek"], wiki: "McArthur–Burney_Falls_Memorial_State_Park" },
  { id: "mount-shasta", name: "Mount Shasta & Castle Crags", lat: 41.3099, lon: -122.3106, area: "sierra", tags: ["mountains", "hiking", "lakes", "sacred", "offbeat"], fee: 0, stay: "camp", trip: "weekend",
    note: "A lone volcano with crystal shops in town, McCloud's three waterfalls and granite spires.",
    days: ["McCloud Falls (lower, middle, upper), the Mount Shasta headwaters spring", "Castle Crags trail, Lake Siskiyou swim"], wiki: "Mount_Shasta" },
  { id: "feather-falls", name: "Feather Falls", lat: 39.6430, lon: -121.2690, area: "foothills", tags: ["hiking", "nature"], fee: 0, stay: null, trip: "day",
    note: "A 400-foot waterfall at the end of a forest trail near Lake Oroville.",
    days: ["Feather Falls loop (about 9 miles), Oroville Dam overlook"], wiki: "Feather_Falls" },
  { id: "bidwell-park", name: "Bidwell Park", lat: 39.7700, lon: -121.7900, area: "valley", tags: ["hiking", "lakes", "cycling", "nature"], fee: 0, stay: null, trip: "local",
    note: "Swimming holes in Big Chico Creek, one of the largest city parks in the country.",
    days: ["Bike to Bear Hole and Salmon Hole, sunset on Monkey Face"], wiki: "Bidwell_Park" },
  // ---------------------------------------------------------------- Far north
  { id: "redwoods", name: "Redwood National Park", lat: 41.2132, lon: -124.0046, area: "north_coast", tags: ["nature", "hiking", "wildlife", "film", "beach"], fee: 12, stay: "camp", trip: "both",
    note: "The tallest trees on Earth, Roosevelt elk and Fern Canyon from Jurassic Park.",
    days: ["Fern Canyon (wet feet), Gold Bluffs Beach elk", "Tall Trees Grove (free permit), Klamath overlook"], wiki: "Redwood_National_and_State_Parks" },
  { id: "avenue-of-giants", name: "Avenue of the Giants", lat: 40.3518, lon: -123.9254, area: "north_coast", tags: ["nature", "hiking", "offbeat"], fee: 0, stay: "camp", trip: "weekend",
    note: "A 31-mile road through old-growth redwoods, with drive-through and walk-through trees.",
    days: ["Founders Grove, Rockefeller Forest loop, swim in the Eel River", "Shrine drive-thru tree, Ferndale's Victorian main street"], wiki: "Avenue_of_the_Giants" },
  { id: "lost-coast", name: "Lost Coast (Shelter Cove)", lat: 40.0300, lon: -124.0730, area: "north_coast", tags: ["offbeat", "hiking", "beach", "views", "camping"], fee: 0, stay: "camp", trip: "weekend",
    note: "The coast so rugged Highway 1 gave up: black sand beaches and almost nobody else.",
    days: ["Drive the switchbacks to Shelter Cove, Black Sands Beach tide pools", "Hike a stretch of the Lost Coast Trail at low tide"], wiki: "Lost_Coast" },
  { id: "trinidad", name: "Trinidad & Moonstone Beach", lat: 41.0590, lon: -124.1431, area: "north_coast", tags: ["beach", "views", "villages", "hiking", "food"], fee: 0, stay: null, trip: "local",
    note: "A tiny harbor town with sea stacks, tide pools and a lighthouse on a hill.",
    days: ["Trinidad Head trail, tide pools at Moonstone Beach, fish tacos by the pier"], wiki: "Trinidad,_California" },
  { id: "sue-meg", name: "Sue-meg State Park", lat: 41.1370, lon: -124.1580, area: "north_coast", tags: ["nature", "hiking", "beach", "history", "wildlife"], fee: 8, stay: "camp", trip: "local",
    note: "Agate Beach, Wedding Rock and a rebuilt Yurok village on the cliffs north of Trinidad.",
    days: ["Rim Trail to Wedding Rock, hunt for agates on Agate Beach, visit Sumêg Village"], wiki: "Sue-meg_State_Park" },
  { id: "ferndale", name: "Ferndale & Centerville Beach", lat: 40.5762, lon: -124.2639, area: "north_coast", tags: ["villages", "architecture", "film", "beach", "offbeat"], fee: 0, stay: null, trip: "local",
    note: "A whole town of painted Victorian 'butterfat palaces', then a wild empty beach.",
    days: ["Main Street's Victorian storefronts and candy shop, Russ Park trails, sunset at Centerville Beach"], wiki: "Ferndale,_California" },
  { id: "crater-lake", name: "Crater Lake (Oregon)", lat: 42.9446, lon: -122.1090, area: "sierra_high", tags: ["lakes", "views", "hiking", "nature", "snow"], fee: 30, stay: "camp", trip: "weekend",
    note: "The deepest lake in the US, impossibly blue inside a collapsed volcano.",
    days: ["Rim Drive viewpoints (summer), Cleetwood Cove swim", "Watchman Peak sunset, Plaikni Falls trail"], wiki: "Crater_Lake" },
  // ---------------------------------------------------------------- Central coast (Cal Poly country)
  { id: "hearst-castle", name: "Hearst Castle & San Simeon", lat: 35.6852, lon: -121.1682, area: "coast", tags: ["history", "architecture", "wildlife", "castles"], fee: 0, ticket: 35, stay: "camp", trip: "both",
    note: "A newspaper tycoon's hilltop castle with a marble pool, and elephant seals below it.",
    days: ["Hearst Castle tour, zebras grazing by the road, Piedras Blancas elephant seals", "Cambria's Moonstone Beach boardwalk, Ragged Point"], wiki: "Hearst_Castle" },
  { id: "morro-bay", name: "Morro Bay & Montaña de Oro", lat: 35.3658, lon: -120.8499, area: "coast", tags: ["hiking", "wildlife", "beach", "views", "food"], fee: 0, stay: "camp", trip: "both",
    note: "Sea otters under Morro Rock and wild bluff trails in Montaña de Oro.",
    days: ["Kayak the back bay with otters, fish and chips on the Embarcadero", "Montaña de Oro bluffs trail, Valencia Peak, Spooner's Cove"], wiki: "Montaña_de_Oro_State_Park" },
  { id: "bishop-peak", name: "Bishop Peak", lat: 35.3030, lon: -120.6966, area: "coast", tags: ["hiking", "views", "climbing"], fee: 0, stay: null, trip: "local",
    note: "SLO's favorite sunset hike up one of the Nine Sisters volcanic peaks.",
    days: ["Sunset hike, then Thursday night farmers market downtown"], wiki: "Bishop_Peak" },
  { id: "avila-beach", name: "Avila Beach & Sycamore Springs", lat: 35.1800, lon: -120.7310, area: "coast", tags: ["beach", "spas", "hiking", "views"], fee: 0, ticket: 20, stay: null, trip: "local",
    note: "A warm-water cove, the Pecho Coast lighthouse hike and hillside hot tubs.",
    days: ["Bob Jones trail by bike, Avila's beach, a hot tub at Sycamore Mineral Springs"], wiki: "Avila_Beach,_California" },
  { id: "pismo-dunes", name: "Pismo Beach & Oceano Dunes", lat: 35.1428, lon: -120.6413, area: "coast", tags: ["beach", "surf", "desert", "food", "offbeat"], fee: 10, stay: "camp", trip: "both",
    note: "Drive or sandboard on the only beach dunes you can camp on, then clam chowder in Pismo.",
    days: ["Rent a sandboard at the Oceano Dunes, Pismo pier at sunset", "Monarch butterfly grove (winter), Guadalupe-Nipomo Dunes"], wiki: "Oceano_Dunes_State_Vehicular_Recreation_Area" },
  { id: "solvang", name: "Solvang & Los Olivos", lat: 34.5958, lon: -120.1376, area: "wine", tags: ["villages", "wine", "food", "offbeat"], fee: 0, stay: "motel", trip: "both",
    note: "A Danish-style village with windmills and aebleskiver, next to Santa Ynez wine country.",
    days: ["Aebleskiver breakfast, windmills, Los Olivos tasting rooms", "Lake Cachuma eagle cruise (winter), Nojoqui Falls"], wiki: "Solvang,_California" },
  { id: "santa-barbara", name: "Santa Barbara", lat: 34.4208, lon: -119.6982, area: "coast", tags: ["beach", "food", "wine", "hiking", "architecture", "nightlife"], fee: 0, stay: "hostel", trip: "both",
    note: "Spanish-revival streets, the Funk Zone's tasting rooms and Inspiration Point above it all.",
    days: ["The courthouse clock tower view, State Street, Funk Zone", "Inspiration Point hike, Butterfly Beach, tacos at La Super-Rica"], wiki: "Santa_Barbara,_California" },
  { id: "gaviota", name: "Gaviota Hot Springs & Peak", lat: 34.4950, lon: -120.2190, area: "coast", tags: ["hiking", "spas", "views", "offbeat"], fee: 10, stay: null, trip: "local",
    note: "A short hike to wild sulfur pools, then on up to ocean views and the Gaviota wind caves.",
    days: ["Hot springs trail, Gaviota Peak, the wind caves at sunset"], wiki: "Gaviota_State_Park" },
  { id: "ojai", name: "Ojai", lat: 34.4480, lon: -119.2429, area: "foothills", tags: ["spas", "hiking", "villages", "views", "books"], fee: 0, stay: "motel", trip: "both",
    note: "An artsy valley known for its 'pink moment' sunset and an outdoor bookstore.",
    days: ["Bart's Books (outdoor shelves), Ojai Avenue, Meditation Mount at the pink moment", "Rose Valley Falls, the Ojai Valley trail by bike"], wiki: "Ojai,_California" },
  { id: "channel-islands", name: "Channel Islands", lat: 34.0490, lon: -119.5570, port: [34.2478, -119.2649, "Ventura Harbor"], area: "coast", tags: ["islands", "hiking", "wildlife", "caves", "camping"], fee: 0, ticket: 75, stay: "camp", trip: "both",
    note: "A boat to 'California's Galápagos': island foxes, dolphins on the way and sea-cave kayaking.",
    days: ["Boat from Ventura to Scorpion Anchorage, Cavern Point loop", "Sea cave kayak tour, Potato Harbor"], wiki: "Channel_Islands_National_Park" },
  { id: "point-mugu", name: "Point Mugu", lat: 34.0850, lon: -119.0600, area: "coast", tags: ["hiking", "beach", "views"], fee: 10, stay: null, trip: "local",
    note: "A sand dune you can run down to the ocean and canyon trails behind it.",
    days: ["Mugu Peak loop, run down the Sycamore Cove dune, Neptune's Net for fried fish"], wiki: "Point_Mugu_State_Park" },
  // ---------------------------------------------------------------- Los Angeles and around
  { id: "los-angeles", name: "Los Angeles", lat: 34.1184, lon: -118.3004, area: "city", tags: ["film", "views", "food", "art", "nightlife", "streetart", "music", "vintage"], fee: 15, stay: "hostel", trip: "both",
    note: "Griffith Observatory over the lights, Koreatown at midnight and the Broad's mirror rooms.",
    days: ["Griffith Observatory hike at sunset, Los Feliz", "The Broad and Grand Central Market, the Arts District murals, Koreatown BBQ"], wiki: "Los_Angeles" },
  { id: "malibu", name: "Malibu (El Matador & Point Dume)", lat: 34.0383, lon: -118.8750, area: "coast", tags: ["beach", "views", "surf", "hiking"], fee: 10, stay: null, trip: "local",
    note: "Sea stacks and caves at El Matador, and whale-watching from Point Dume's bluff.",
    days: ["El Matador at low tide, Point Dume's bluff trail, sunset at Zuma"], wiki: "El_Matador_State_Beach" },
  { id: "sandstone-peak", name: "Sandstone Peak", lat: 34.1220, lon: -118.9320, area: "foothills", tags: ["hiking", "views", "climbing"], fee: 0, stay: null, trip: "local",
    note: "The highest point in the Santa Monica Mountains, with Channel Islands views.",
    days: ["Mishe Mokwa loop past Balanced Rock to the summit"], wiki: "Sandstone_Peak" },
  { id: "venice", name: "Venice & Santa Monica", lat: 33.9850, lon: -118.4695, area: "coast", tags: ["beach", "streetart", "nightlife", "cycling", "food", "vintage"], fee: 10, stay: null, trip: "local",
    note: "The skatepark, the canals and a bike ride along the boardwalk to the pier.",
    days: ["Venice canals, skatepark, bike to the Santa Monica Pier at sunset"], wiki: "Venice,_Los_Angeles" },
  { id: "eaton-canyon", name: "Eaton Canyon Falls", lat: 34.1788, lon: -118.0960, area: "foothills", tags: ["hiking", "nature"], fee: 0, stay: null, trip: "local",
    note: "A creek-hopping walk to a waterfall, 15 minutes from Pasadena.",
    days: ["Eaton Canyon Falls trail, then Old Town Pasadena"], wiki: "Eaton_Canyon" },
  { id: "palos-verdes", name: "Palos Verdes", lat: 33.7440, lon: -118.4090, area: "coast", tags: ["views", "beach", "wildlife", "hiking"], fee: 5, stay: null, trip: "local",
    note: "Tide pools, a sea arch and the Portuguese Bend coves on LA's quiet peninsula.",
    days: ["Abalone Cove tide pools, Point Vicente whale watch, Terranea's cliff trail at sunset"], wiki: "Palos_Verdes_Peninsula" },
  { id: "catalina", name: "Catalina Island", lat: 33.3428, lon: -118.3278, port: [33.7520, -118.2010, "the Long Beach ferry terminal"], area: "coast", tags: ["islands", "beach", "hiking", "wildlife", "views"], fee: 0, ticket: 80, stay: "camp", trip: "both",
    note: "A ferry to a car-free island town with bison, snorkeling and golf carts.",
    days: ["Ferry to Avalon, snorkel at Lovers Cove, the Casino building", "Hike to the Garden to Sky trail, look for bison on an inland tour"], wiki: "Santa_Catalina_Island_(California)" },
  { id: "mount-baldy", name: "Mount Baldy", lat: 34.2889, lon: -117.6467, area: "socal_mtn", tags: ["hiking", "snow", "mountains", "views"], fee: 5, stay: null, trip: "local",
    note: "A 10,000-foot summit above LA, with a ski lift and a lodge serving chili.",
    days: ["Devils Backbone trail to the summit, or the lift and the Top of the Notch"], wiki: "Mount_San_Antonio" },
  { id: "big-bear", name: "Big Bear Lake", lat: 34.2439, lon: -116.9114, area: "socal_mtn", tags: ["snow", "lakes", "hiking", "mountains", "cycling"], fee: 5, stay: "cabin", trip: "both",
    note: "Snowboarding at the closest real ski resort to LA, or kayaking the lake in summer.",
    days: ["Ski or snowboard at Bear Mountain (or kayak in summer), the Village", "Castle Rock trail, Big Bear Alpine Zoo"], wiki: "Big_Bear_Lake,_California" },
  { id: "lake-arrowhead", name: "Lake Arrowhead", lat: 34.2483, lon: -117.1890, area: "socal_mtn", tags: ["lakes", "mountains", "hiking", "snow"], fee: 5, stay: "cabin", trip: "local",
    note: "A pine-forest lake an hour from campus, with the Heaps Peak trail and fall colors.",
    days: ["Lake Arrowhead Village, the Arrowhead Queen boat, Heaps Peak arboretum"], wiki: "Lake_Arrowhead,_California" },
  { id: "mount-rubidoux", name: "Mount Rubidoux", lat: 33.9810, lon: -117.3880, area: "valley", tags: ["hiking", "views", "history"], fee: 0, stay: null, trip: "local",
    note: "Riverside's sunrise hill, topped with a stone bridge and a peace tower.",
    days: ["Sunrise loop to the summit cross, breakfast at the Mission Inn district"], wiki: "Mount_Rubidoux" },
  { id: "idyllwild", name: "Idyllwild", lat: 33.7400, lon: -116.7189, area: "socal_mtn", tags: ["hiking", "villages", "climbing", "mountains", "camping"], fee: 5, stay: "camp", trip: "both",
    note: "A mountain village with a dog as mayor, Tahquitz Rock and trails to San Jacinto Peak.",
    days: ["Ernie Maxwell trail, village coffee, Suicide Rock climbers", "San Jacinto Peak via Devils Slide, or ride the Palm Springs tram down"], wiki: "Idyllwild–Pine_Cove,_California" },
  { id: "palm-springs", name: "Palm Springs", lat: 33.8303, lon: -116.5453, area: "desert", tags: ["spas", "hiking", "architecture", "nightlife", "lgbtq", "desert"], fee: 0, ticket: 15, stay: "motel", trip: "both",
    note: "Midcentury pool motels, palm oases in Indian Canyons and a rotating tram up the mountain.",
    days: ["Indian Canyons' palm oasis trail, midcentury home tour, pool afternoon", "Aerial Tramway to the snow line, the Thursday VillageFest"], wiki: "Palm_Springs,_California" },
  { id: "joshua-tree", name: "Joshua Tree", lat: 33.8734, lon: -115.9010, area: "desert", tags: ["desert", "climbing", "hiking", "stargazing", "camping", "art", "offbeat"], fee: 30, stay: "camp", trip: "both",
    note: "Twisted trees, boulder scrambles and some of the darkest skies near LA.",
    days: ["Hidden Valley loop, Skull Rock, Keys View sunset, stargazing", "Cholla Cactus Garden at sunrise, Noah Purifoy's outdoor art museum"], wiki: "Joshua_Tree_National_Park" },
  { id: "salvation-mountain", name: "Salvation Mountain & Salton Sea", lat: 33.2541, lon: -115.4727, area: "desert", tags: ["offbeat", "art", "film", "desert"], fee: 0, stay: "camp", trip: "weekend",
    note: "A hand-painted hill, Slab City's off-grid art town and the eerie shores of the Salton Sea.",
    days: ["Salvation Mountain, East Jesus art garden, Slab City", "Bombay Beach's art installations, the sea's fish-bone beaches"], wiki: "Salvation_Mountain" },
  { id: "anza-borrego", name: "Anza-Borrego & Borrego Springs", lat: 33.2559, lon: -116.3750, area: "desert", tags: ["desert", "stargazing", "nature", "art", "hiking", "camping"], fee: 10, stay: "camp", trip: "both",
    note: "Giant metal dinosaur sculptures in the desert, wildflowers in spring and a dark-sky town.",
    days: ["Galleta Meadows sculptures, Borrego Palm Canyon oasis (bighorn sheep)", "Slot canyon hike, Fonts Point at sunrise"], wiki: "Anza-Borrego_Desert_State_Park" },
  // ---------------------------------------------------------------- Orange County and San Diego
  { id: "laguna-beach", name: "Laguna Beach", lat: 33.5427, lon: -117.7854, area: "coast", tags: ["beach", "art", "views", "wildlife"], fee: 0, stay: null, trip: "local",
    note: "Hidden coves, tide pools and the Thousand Steps beach.",
    days: ["Thousand Steps Beach, Treasure Island tide pools, gallery walk"], wiki: "Laguna_Beach,_California" },
  { id: "crystal-cove", name: "Crystal Cove", lat: 33.5719, lon: -117.8380, area: "coast", tags: ["beach", "hiking", "history"], fee: 15, stay: null, trip: "local",
    note: "Restored 1930s beach cottages, tide pools and the Shake Shack on the bluff.",
    days: ["Crystal Cove historic district, El Moro canyon trail, a date shake"], wiki: "Crystal_Cove_State_Park" },
  { id: "huntington", name: "Huntington Beach", lat: 33.6595, lon: -117.9988, area: "coast", tags: ["surf", "beach", "nightlife", "food"], fee: 15, stay: null, trip: "local",
    note: "Surf City USA: learn to surf by the pier, bonfire pits at night.",
    days: ["Surf lesson by the pier, Main Street, beach bonfire at sunset"], wiki: "Huntington_Beach,_California" },
  { id: "temecula", name: "Temecula wine country", lat: 33.5100, lon: -117.0300, area: "wine", tags: ["wine", "food", "views"], fee: 0, stay: "motel", trip: "both",
    note: "Hot-air balloons at sunrise and relaxed wineries in rolling hills.",
    days: ["Sunrise balloon watch, two tastings on Rancho California Road", "Old Town Temecula, Santa Rosa Plateau vernal pools"], wiki: "Temecula_Valley_AVA" },
  { id: "julian", name: "Julian", lat: 33.0787, lon: -116.6020, area: "socal_mtn", tags: ["villages", "food", "history", "hiking"], fee: 0, stay: "cabin", trip: "both",
    note: "A Gold Rush mountain town famous for apple pie, with snow a few times a winter.",
    days: ["Apple pie on Main Street, Eagle Mine tour, Volcan Mountain", "Cedar Creek Falls (permit), Stonewall Peak"], wiki: "Julian,_California" },
  { id: "san-diego", name: "San Diego", lat: 32.7341, lon: -117.1446, area: "city", tags: ["food", "art", "history", "beach", "nightlife", "gardens"], fee: 0, stay: "hostel", trip: "both",
    note: "Balboa Park's gardens, tacos in Barrio Logan and sunsets at Sunset Cliffs.",
    days: ["Balboa Park's gardens and free museum days, Little Italy", "Chicano Park murals, tacos, Sunset Cliffs at golden hour"], wiki: "San_Diego" },
  { id: "la-jolla", name: "La Jolla Cove", lat: 32.8503, lon: -117.2713, area: "coast", tags: ["wildlife", "beach", "views", "surf", "caves"], fee: 0, stay: null, trip: "local",
    note: "Sea lions on the rocks, kayaking into sea caves and snorkeling with leopard sharks (summer).",
    days: ["Sea lions at the cove, Sunny Jim Cave, kayak or snorkel the Shores"], wiki: "La_Jolla_Cove" },
  { id: "torrey-pines", name: "Torrey Pines", lat: 32.9206, lon: -117.2526, area: "coast", tags: ["hiking", "views", "beach", "nature"], fee: 15, stay: null, trip: "local",
    note: "Sandstone bluffs with the rarest pine in the US, down to Black's Beach.",
    days: ["Razor Point and Beach trails, then down to the beach at low tide"], wiki: "Torrey_Pines_State_Natural_Reserve" },
  { id: "sunset-cliffs", name: "Sunset Cliffs", lat: 32.7239, lon: -117.2541, area: "coast", tags: ["views", "surf", "beach"], fee: 0, stay: null, trip: "local",
    note: "Sea caves and arches lit orange at sunset in Ocean Beach.",
    days: ["OB pier and Newport Ave, Sunset Cliffs at golden hour"], wiki: "Sunset_Cliffs" },
  { id: "moonlight-beach", name: "Encinitas & Moonlight Beach", lat: 33.0480, lon: -117.2970, area: "coast", tags: ["beach", "surf", "gardens", "food"], fee: 0, stay: null, trip: "local",
    note: "Swami's surf break below a golden-domed meditation garden.",
    days: ["Self-Realization Fellowship gardens, Swami's, acai bowls on the 101"], wiki: "Encinitas,_California" },
  // ---------------------------------------------------------------- Deserts and beyond
  { id: "death-valley", name: "Death Valley", lat: 36.4570, lon: -116.8660, area: "desert", tags: ["desert", "stargazing", "hiking", "offbeat", "views", "camping"], fee: 30, stay: "camp", trip: "weekend",
    note: "Salt flats below sea level, rainbow-colored hills and the darkest night sky in California.",
    days: ["Zabriskie Point at sunrise, Golden Canyon, Badwater Basin salt flats", "Mesquite dunes at sunset, Artists Palette, stargazing"], wiki: "Death_Valley_National_Park" },
  { id: "calico", name: "Calico Ghost Town", lat: 34.9486, lon: -116.8650, area: "desert", tags: ["history", "offbeat", "desert"], fee: 0, ticket: 8, stay: "camp", trip: "day",
    note: "A silver-mining boomtown on the way to Vegas, with a mine you can walk into.",
    days: ["Maggie Mine walk, the town's wooden streets, Peggy Sue's 50s Diner"], wiki: "Calico_Ghost_Town" },
  { id: "mojave", name: "Mojave Preserve & Kelso Dunes", lat: 34.9073, lon: -115.7181, area: "desert", tags: ["desert", "offbeat", "camping", "stargazing", "hiking"], fee: 0, stay: "camp", trip: "weekend",
    note: "Booming sand dunes that hum when you slide down, and free camping under the stars.",
    days: ["Kelso Depot, climb the Kelso Dunes at sunset", "Hole-in-the-Wall rings trail, Cima Dome's Joshua tree forest"], wiki: "Kelso_Dunes" },
  { id: "las-vegas", name: "Las Vegas (Nevada)", lat: 36.1147, lon: -115.1728, area: "desert", tags: ["nightlife", "music", "food", "themeparks", "offbeat"], fee: 0, stay: "motel", trip: "weekend",
    note: "The Strip's free shows, the Neon Museum's sign boneyard and cheap Sunday-night rooms.",
    days: ["The Strip at night, the Bellagio fountains and conservatory (free), Fremont Street", "The Neon Museum (book ahead), Seven Magic Mountains' painted boulders south of town", "Hoover Dam and the Mike O'Callaghan bridge walk"], wiki: "Las_Vegas" },
  { id: "valley-of-fire", name: "Valley of Fire (Nevada)", lat: 36.4300, lon: -114.5130, area: "desert", tags: ["desert", "hiking", "views", "offbeat", "camping", "stargazing"], fee: 15, stay: "camp", trip: "weekend",
    note: "Swirling red and pink sandstone, petroglyphs and the Fire Wave, an hour past Las Vegas.",
    days: ["Fire Wave and White Domes trails (go early: no shade), camp at Atlatl Rock", "Mouse's Tank petroglyphs, Elephant Rock, sunset at Rainbow Vista"], wiki: "Valley_of_Fire_State_Park" },
  { id: "sedona", name: "Sedona (Arizona)", lat: 34.8697, lon: -111.7610, area: "high_desert", tags: ["hiking", "views", "offbeat", "stargazing", "spas", "nature"], fee: 5, stay: "camp", trip: "long",
    note: "Red rock buttes, slot-canyon swimming holes and a dark-sky town (Red Rock Pass $5 a car).",
    days: ["Cathedral Rock at sunset, dinner in Uptown Sedona", "Devil's Bridge at sunrise, swim at Slide Rock State Park", "Chapel of the Holy Cross, Bell Rock pathway"], wiki: "Sedona,_Arizona" },
  { id: "grand-canyon", name: "Grand Canyon South Rim (Arizona)", lat: 36.0544, lon: -112.1401, area: "high_desert", tags: ["views", "hiking", "nature", "camping", "stargazing"], fee: 35, stay: "camp", trip: "long",
    note: "The Rim Trail at sunset and a few switchbacks into the canyon (going down is optional, up is not).",
    days: ["Mather Point and Yavapai Geology Museum at sunset", "South Kaibab trail to Ooh Aah Point or Cedar Ridge, Hermit Road shuttle", "Desert View Watchtower at sunrise"], wiki: "Grand_Canyon_National_Park" },
  { id: "great-basin", name: "Great Basin (Nevada)", lat: 39.0055, lon: -114.2200, area: "sierra_high", tags: ["stargazing", "caves", "hiking", "offbeat", "camping", "mountains"], fee: 0, ticket: 15, stay: "camp", trip: "long",
    note: "The least-visited big national park: 4,000-year-old bristlecone pines, a marble cave and some of the darkest skies in the country.",
    days: ["Arrive via Highway 50, 'the loneliest road in America', ranger astronomy talk", "Lehman Caves tour (book ahead), bristlecone pine grove trail", "Wheeler Peak scenic drive and alpine lakes loop"], wiki: "Great_Basin_National_Park" },
  { id: "reno", name: "Reno (Nevada)", lat: 39.5296, lon: -119.8138, area: "high_desert", tags: ["nightlife", "food", "art", "lakes", "offbeat"], fee: 0, stay: "motel", trip: "weekend",
    note: "Cheap rooms, Midtown's murals and bars, tubing the Truckee River and Tahoe's east shore 40 minutes away.",
    days: ["Midtown murals and food, the Riverwalk at night", "Sand Harbor on Lake Tahoe's east shore, then Virginia City's old boardwalks"], wiki: "Reno,_Nevada" },
  { id: "ashland", name: "Ashland (Oregon)", lat: 42.1946, lon: -122.7095, area: "foothills", tags: ["art", "music", "villages", "food", "hiking"], fee: 0, stay: "motel", trip: "weekend",
    note: "The Oregon Shakespeare Festival (Feb–Oct, cheap student rush tickets) in a small town with no sales tax.",
    days: ["Lithia Park, a play at the Oregon Shakespeare Festival", "Lithia Springs water fountain (it's strong), hike Grizzly Peak, Jacksonville's old town"], wiki: "Ashland,_Oregon" },
  { id: "boardman", name: "Southern Oregon coast", lat: 42.1370, lon: -124.3530, area: "north_coast", tags: ["beach", "views", "hiking", "nature", "camping"], fee: 0, stay: "camp", trip: "weekend",
    note: "Natural Bridges, Secret Beach and sea stacks on the Samuel H. Boardman corridor, just over the border.",
    days: ["Natural Bridges viewpoint, Secret Beach at low tide", "Arch Rock, Whaleshead Beach, Brookings' redwoods"], wiki: "Samuel_H._Boardman_State_Scenic_Corridor" },
  { id: "zion", name: "Zion (Utah)", lat: 37.2982, lon: -113.0263, area: "high_desert", tags: ["hiking", "views", "nature", "camping", "mountains"], fee: 35, stay: "camp", trip: "long",
    note: "Wade up the Narrows slot canyon and hike Angels Landing (permit lottery).",
    days: ["Pa'rus trail at sunset, dinner in Springdale", "The Narrows bottom-up (rent canyoneering shoes in Springdale)", "Canyon Overlook trail at sunrise"], wiki: "Zion_National_Park" },
  // ---------------------------------------------------------------- Valley local finds
  { id: "forestiere", name: "Forestiere Underground Gardens", lat: 36.8070, lon: -119.8820, area: "valley", tags: ["offbeat", "gardens", "history", "architecture"], fee: 0, ticket: 25, stay: null, trip: "local",
    note: "A Sicilian immigrant's hand-dug underground home with fruit trees growing through skylights.",
    days: ["Guided tour of the underground rooms, then Tower District food"], wiki: "Forestiere_Underground_Gardens" },
  { id: "knights-ferry", name: "Knights Ferry", lat: 37.8180, lon: -120.5750, area: "foothills", tags: ["history", "lakes", "offbeat"], fee: 0, stay: null, trip: "local",
    note: "The longest covered bridge west of the Mississippi, and rafting on the Stanislaus River.",
    days: ["Covered bridge, an easy river raft or kayak, picnic by the mill ruins"], wiki: "Knights_Ferry,_California" },
  { id: "san-luis-reservoir", name: "Pacheco Pass & Casa de Fruta", lat: 37.0040, lon: -121.2290, area: "valley", tags: ["offbeat", "food", "views"], fee: 0, stay: null, trip: "local",
    note: "A roadside fruit stand turned small amusement stop, and hills that go green in winter.",
    days: ["Casa de Fruta's dried fruit and train, San Luis Reservoir viewpoint"], wiki: "Casa_de_Fruta" }
];
