#!/usr/bin/env node
// Builds us/index.html, the California version of Weekender, from index.html, so both versions share
// one codebase (every screen and feature) and only differ in data and wording. The page loads
// data/us-data.js (written by scripts/build-us.mjs) and assets/us.js, which turns colleges into
// "home cities" and places into local finds, day trips and weekend trips by car.
// Run after editing index.html: node scripts/build-us-page.mjs (the tests check it's up to date).
import fs from "node:fs";

const ROOT = new URL("..", import.meta.url).pathname;
const src = fs.readFileSync(ROOT + "index.html", "utf8");
const usData = fs.readFileSync(ROOT + "data/us-data.js", "utf8");
const usJs = fs.readFileSync(ROOT + "assets/us.js", "utf8");
// Version stamps so browsers fetch new copies after each change.
const stamp = (s) => { let h = 0; for (const c of s) h = (h * 31 + c.charCodeAt(0)) >>> 0; return h.toString(16); };

let html = src;
function swap(from, to) {
  const n = html.split(from).length - 1;
  if (n < 1) throw new Error(`build-us-page: text not found in index.html: ${from.slice(0, 80)}`);
  html = html.split(from).join(to);
}
swap(/* links resolve from the site root, and the app knows which version it is */
  `<meta charset="utf-8">`, `<meta charset="utf-8">\n<base href="../">\n<script>window.REGION = "us";</script>`);
html = html.replace(/<script src="data\/app-data\.js\?v=[^"]*"><\/script>/,
  `<script src="data/us-data.js?v=${stamp(usData)}"></script>\n<script src="assets/us.js?v=${stamp(usJs)}"></script>`);
if (!html.includes("data/us-data.js")) throw new Error("build-us-page: app-data script tag not found");

const TITLE = "Weekender: weekend trips for California college students";
swap("<title>Weekender: cheap weekend trips for students abroad</title>", `<title>${TITLE}</title>`);
swap(`<meta property="og:title" content="Weekender: cheap weekend trips for students abroad">`, `<meta property="og:title" content="${TITLE}">`);
swap(`content="Plan a cheap weekend away from where you're studying abroad: 120 European cities scored 1 to 10 on price, timing and your interests, with budgets and day-by-day plans built from open data."`,
  `content="Pick your California college and get local finds, day trips and weekend road trips scored 1 to 10, with gas split between friends, park fees, campsites and day-by-day plans built from open data."`);
swap(`content="Pick your home city, budget and interests; get scored trips with costs, transport and a tailored itinerary."`,
  `content="Pick your college, budget and interests; get local finds, day trips and weekend road trips with real drive times and costs."`);
swap(`<meta property="og:url" content="https://weekender-trips.com/">`, `<meta property="og:url" content="https://weekender-trips.com/us/">`);
swap("shown on a map of Europe", "for California college students");
swap(`placeholder="Search a city"`, `placeholder="Search your college"`);
swap(">Where are you based?</label>", ">Where do you go to college?</label>");
swap("<p>Real prices for 120 cities and 640+ day trips, scored 1–10 for you.</p>",
  `<p>${new Set(JSON.parse(usData.slice(usData.indexOf("{"), usData.lastIndexOf("}") + 1)).colleges.map(c => c.id)).size} California colleges, hidden local spots, day trips and weekend road trips, scored 1–10 for you.</p>`);
swap("<b>Pick your city and budget</b><span>Where you're studying, when, and what you want to spend.</span>",
  "<b>Pick your college and budget</b><span>Your campus, when, and what you want to spend.</span>");
swap("<span>Price, weather, crowds and what you're into, in one number.</span>",
  "<span>Drive time, gas split three ways, park fees, weather and what you're into, in one number.</span>");
swap("Built on 5 years of weather records, official tourism and price statistics, OpenStreetMap and real flight fares.",
  "Built on real driving routes (OSRM), 5 years of weather records (Open-Meteo), OpenStreetMap, Wikipedia and current gas prices.");

fs.mkdirSync(ROOT + "us", { recursive: true });
const out = html.replace("<!doctype html>\n", "<!doctype html>\n<!-- Generated by scripts/build-us-page.mjs from index.html: edit index.html, then rerun. -->\n");
if (process.argv.includes("--check")) {
  const now = fs.existsSync(ROOT + "us/index.html") ? fs.readFileSync(ROOT + "us/index.html", "utf8") : "";
  if (now !== out) { console.error("us/index.html is out of date: run node scripts/build-us-page.mjs"); process.exit(1); }
  console.log("us/index.html is up to date");
} else {
  fs.writeFileSync(ROOT + "us/index.html", out);
  console.log(`wrote us/index.html (${(out.length / 1024).toFixed(0)} KB)`);
}
