#!/usr/bin/env node
// Writes the parts of data/city-data.json the app needs to data/app-data.js, and points index.html at
// the new version (data/app-data.js?v=<hash>) so browsers fetch fresh data after each refresh.
import fs from "node:fs/promises";
import { createHash } from "node:crypto";

const ROOT = new URL("..", import.meta.url).pathname;
const data = JSON.parse(await fs.readFile(ROOT + "data/city-data.json", "utf8"));
const keep = ["season", "priceMult", "costs", "interests", "strengths", "climate", "crowds", "price", "osm", "wikipedia", "popularity"];
const compact = {
  generated: data.generated, sources: data.sources, method: data.method, osm: data.osm, roads: data.roads || {},
  fares: data.fares ? { fetched: data.fares.fetched, months: data.fares.months, prices: data.fares.prices } : null, // history stays in city-data.json
  nearby: JSON.parse(await fs.readFile(ROOT + "data/nearby-airports.json", "utf8")).cities,
  flightModel: data.flightModel ? { mean: data.flightModel.mean, std: data.flightModel.std, w: data.flightModel.w, b: data.flightModel.b,
    smear: data.flightModel.smear, enc: data.flightModel.enc, known: data.flightModel.known, n: data.flightModel.n, trained: data.flightModel.trained, test: data.flightModel.test } : null,
  cities: Object.fromEntries(Object.entries(data.cities).map(([id, c]) => {
    const o = {};
    for (const k of keep) if (c[k] != null) o[k] = c[k];
    if (o.climate) delete o.climate.comfort;
    if (o.wikipedia) o.wikipedia = { title: o.wikipedia.title, monthlyViews: o.wikipedia.monthlyViews };
    return [id, o];
  }))
};
const js = "// Generated by scripts/embed-data.mjs from data/city-data.json. Do not edit by hand.\nwindow.CITY_DATA = " + JSON.stringify(compact) + ";\n";
await fs.writeFile(ROOT + "data/app-data.js", js);
const v = createHash("sha1").update(js).digest("hex").slice(0, 10);
const html = await fs.readFile(ROOT + "index.html", "utf8");
if (!/data\/app-data\.js\?v=[\w]+/.test(html)) throw new Error("data/app-data.js script tag not found in index.html");
await fs.writeFile(ROOT + "index.html", html.replace(/data\/app-data\.js\?v=[\w]+/, "data/app-data.js?v=" + v));
console.log(`wrote data for ${Object.keys(compact.cities).length} cities (${Math.round(js.length / 1024)} KB), v=${v}`);
